version: '3' # Docker Compose 파일의 버전을  명시합니다.  여기서는 '3' 버전을  사용합니다.

services: #  여러  서비스(컨테이너)를  정의합니다.
  server: # 첫 번째  서비스의  이름을 'server'로  지정합니다.
    build: ./server #  이  서비스를  위한 Docker  이미지를 빌드할 때  사용할 Dockerfile이 있는 디렉토리를  지정합니다.
    ports:
      - "3001:3001" #  호스트와 컨테이너 간의 포트 매핑을 설정합니다.  호스트의  3001 포트를 컨테이너의  3001 포트에  연결합니다.
    volumes:
      - ./server:/app #  호스트와 컨테이너 간의 볼륨을  마운트합니다.  호스트의 ./server 디렉토리를 컨테이너의 /app 디렉토리에  연결합니다.
    environment: # 환경 변수를 설정합니다.  여기서는 NODE_ENV를 'development'로 설정합니다.
      - NODE_ENV=development
    command: npm start # 컨테이너가  시작될 때 실행할  명령어를  지정합니다.  여기서는 'npm start'를 실행합니다.
  nginx: # 두 번째  서비스의  이름을 'nginx'로  지정합니다.
    build: #  이  서비스를  위한 Docker  이미지를 빌드할 때  사용할 Dockerfile과 컨텍스트를  지정합니다.
      context: . #  현재 디렉토리를 빌드 컨텍스트로  사용합니다.
      dockerfile: Dockerfile # 빌드에  사용할 Dockerfile의  이름을  지정합니다.
    ports:
      - "4000:8000" #  호스트와 컨테이너 간의 포트 매핑을 설정합니다.  호스트의  4000 포트를 컨테이너의  8000 포트에  연결합니다.
    depends_on:
      - server #  이  서비스가  시작되기  전에 'server'  서비스가  시작되어야 함을  지정합니다.
